# Generated by Django 3.1.6 on 2021-02-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('style', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
